//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMgmt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inventory> Inventories { get; set; }
    
        public virtual ObjectResult<GetInventory_Result> GetInventory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInventory_Result>("GetInventory");
        }
    
        public virtual ObjectResult<Inventory> Func_GetInventory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Inventory>("Func_GetInventory");
        }
    
        public virtual ObjectResult<Inventory> Func_GetInventory(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Inventory>("Func_GetInventory", mergeOption);
        }
    }
}
